_wandb:
    value:
        cli_version: 0.25.0
        e:
            zv9boi8n5ixjbjor4nitcr2uxkyv5is8:
                args:
                    - --local_rank=0
                    - --save_path
                    - /scratch/m000228/tmp/checkpoint/llama3b-dpo-b32-self-score_sft
                    - --save_steps
                    - "-1"
                    - --logging_steps
                    - "1"
                    - --eval_steps
                    - "-1"
                    - --train_batch_size
                    - "32"
                    - --micro_train_batch_size
                    - "1"
                    - --pretrain
                    - meta-llama/Llama-3.2-3B-Instruct
                    - --param_dtype
                    - bf16
                    - --max_epochs
                    - "1"
                    - --max_len
                    - "8192"
                    - --zero_stage
                    - "3"
                    - --learning_rate
                    - "5e-7"
                    - --beta
                    - "0.1"
                    - --dataset
                    - json@/users/hjnam/sycophancy/train_data/dpo_capability_openrlhf/l3b
                    - --apply_chat_template
                    - --chosen_key
                    - chosen
                    - --rejected_key
                    - rejected
                    - --attn_implementation
                    - flash_attention_2
                    - --load_checkpoint
                    - --packing_samples
                    - --gradient_checkpointing
                    - --use_wandb
                    - 173ea73581c8f47fb8aa18a4b33040f44e4ebdd6
                cpu_count: 112
                cpu_count_logical: 112
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1888556142592"
                        used: "113908174848"
                email: hjnam@stanford.edu
                executable: /projects/m000228/scyophancy/bin/python3.12
                git:
                    commit: 7f32779a1019ac2ec96047b2109b9205aa4e1696
                    remote: https://github.com/OpenRLHF/OpenRLHF.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-fe6c4650-f030-568b-90c4-7d60af62a144
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-778d742a-e4e1-4c3f-0fb7-5f8406b4d62b
                host: n20
                memory:
                    total: "2164228784128"
                os: Linux-5.15.0-1053-nvidia-x86_64-with-glibc2.35
                program: -m openrlhf.cli.train_dpo_capability
                python: CPython 3.12.0
                root: /users/hjnam/OpenRLHF
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/slurm/slurm.conf
                    job_id: "180914"
                startedAt: "2026-02-27T00:18:02.392903Z"
                writerId: zv9boi8n5ixjbjor4nitcr2uxkyv5is8
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": eval/global_step
              "6":
                - 3
              "7": []
            - "2": eval/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 98
            "3":
                - 7
                - 13
                - 16
                - 41
                - 66
            "4": 3.12.0
            "5": 0.25.0
            "6": 5.2.0
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
adam_betas:
    value:
        - 0.9
        - 0.95
adam_offload:
    value: false
apply_chat_template:
    value: true
attn_implementation:
    value: flash_attention_2
aux_loss_coef:
    value: 0
beta:
    value: 0.1
chosen_key:
    value: chosen
ckpt_path:
    value: ./ckpt/checkpoints_dpo
dataset:
    value: json@/users/hjnam/sycophancy/train_data/dpo_capability_openrlhf/l3b
dataset_probs:
    value: null
dataset_split:
    value: train
deepcompile:
    value: false
disable_ds_ckpt:
    value: false
disable_fast_tokenizer:
    value: false
ds_tensor_parallel_size:
    value: 1
eval_dataset:
    value: null
eval_split:
    value: test
eval_steps:
    value: -1
full_determinism:
    value: false
grad_accum_dtype:
    value: null
gradient_checkpointing:
    value: true
gradient_checkpointing_use_reentrant:
    value: false
input_template:
    value: null
ipo:
    value: false
l2:
    value: 0
label_smoothing:
    value: 0
learning_rate:
    value: 5e-07
load_checkpoint:
    value: true
load_in_4bit:
    value: false
local_rank:
    value: 0
logging_steps:
    value: 1
lora_alpha:
    value: 16
lora_dropout:
    value: 0
lora_rank:
    value: 0
lr_scheduler:
    value: cosine_with_min_lr
lr_warmup_ratio:
    value: 0.03
max_ckpt_mem:
    value: 1e+08
max_ckpt_num:
    value: 3
max_epochs:
    value: 1
max_len:
    value: 8192
max_norm:
    value: 1
max_samples:
    value: 1000000
micro_train_batch_size:
    value: 1
min_lr_ratio:
    value: 0.1
nll_loss_coef:
    value: 0
overlap_comm:
    value: false
packing_samples:
    value: true
param_dtype:
    value: bf16
pretrain:
    value: meta-llama/Llama-3.2-3B-Instruct
prompt_key:
    value: null
ref_offload:
    value: false
ref_pretrain:
    value: meta-llama/Llama-3.2-3B-Instruct
rejected_key:
    value: rejected
ring_attn_size:
    value: 1
ring_head_stride:
    value: 1
save_hf_ckpt:
    value: false
save_path:
    value: /scratch/m000228/tmp/checkpoint/llama3b-dpo-b32-self-score_sft
save_steps:
    value: -1
seed:
    value: 42
target_modules:
    value: all-linear
tokenizer_chat_template:
    value: null
train_batch_size:
    value: 32
use_ds_universal_ckpt:
    value: false
use_liger_kernel:
    value: false
use_ms:
    value: false
use_tensorboard:
    value: null
use_wandb:
    value: 173ea73581c8f47fb8aa18a4b33040f44e4ebdd6
wandb_group:
    value: null
wandb_org:
    value: null
wandb_project:
    value: openrlhf_train_dpo
wandb_run_name:
    value: exp_0226T16:17
zero_stage:
    value: 3
zpg:
    value: 1
